### ISSUE TITLE
Roadmap to "stable"

### ISSUE THREAD

**Issue by Ephem** [Ephem/react#12]
Since this is a fork that circles around an unstable React-api and exists solely to fill in the SSR-gap for that until an official solution exists, it will never be "stable" in the traditional sense.

However, at some point I would like to indicate that I'm confident that this is stable enough for use _if you know the tradeoffs and risks you are taking_. This issue will track that progress.

- [x] Benchmark performance (#13)
- [x] Try out Lightyear in a larger app (#14)
- [x] Make sure syncing upstream changes is feasible (#15)
- [x] Improve project infra (#16)
- [x] Improve documentation (#17)

Being considered "stable" will be marked by adopting the versioning strategy proposed in #1, that is, following React major and minor, while keeping patch separate.

**Comment by Ephem** [comment]
Just a quick update on this. Project infra is done, I’m almost done with benchmarks (which are looking good), Lightyear has been tried out in a larger app and I have one more lined up and I expect to make quick work of trying to sync upstream changes and improving documentation after that.

I am on vacation now, but expect to get this done over the next few weeks.

**Comment by Ephem** [comment]
Version 16.9.0 is now released and Lightyear is considered stable! :tada:

This took way longer than I anticipated because of a bunch of (good) personal things that came up at the end of the summer which had to take priority.
